project:
  type: website
  output-dir: docs

website:
  title: "Josefina Bernardo, MSc"
  navbar:
    background: primary
    search: true
    left:
      - text: Home
        href: index.qmd
      - research.qmd
      - resources.qmd
      - cv.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual


